version: "3"

services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /root/.m2:/root/.m2
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
