version: "3"

services:
  jenkins:
    image: jenkinsci/blueocean:1.16.0-bcc31d32159f
    user: root
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"

  sonarqube:
    image: sonarqube:7.7-community
    ports:
      - "9001:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.passowrd=sonar
      - sonar.jdbc.url=jdbc:postgresql://sonar_db/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - sonar_db

  sonar_db:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432

  db:
    image: mysql:8.0.16
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  jenkins-data:

  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:

  postgresql:
  postgresql_data:

  mysql_data:
